@echo off
setlocal

REM Print the fixed PQViewer token generated by setup_windows_path.bat.

set "TOOLS_DIR=%~dp0"
for %%I in ("%TOOLS_DIR%.") do set "TOOLS_DIR=%%~fI"
set "TOKEN_FILE=%TOOLS_DIR%\pqv_token.txt"

if not exist "%TOKEN_FILE%" (
    echo [ERROR] Token file was not found:
    echo   %TOKEN_FILE%
    echo Run tools\setup_windows_path.bat first.
    pause
    exit /b 1
)

set /p PQV_TOKEN=<"%TOKEN_FILE%"

echo %PQV_TOKEN%
echo.
echo Remote setup command:
echo bash tools/setup_remote_path.sh --token %PQV_TOKEN%

pause
